/* This file was generated by SableCC (http://www.sablecc.org/). */

package java.pl.pp.simple.node;

import java.pl.pp.simple.analysis.*;

@SuppressWarnings("nls")
public final class TSemi extends Token
{
    public TSemi(String text)
    {
        setText(text);
    }

    public TSemi(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSemi(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSemi(this);
    }
}
