/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.parser;

import compiler.node.*;
import compiler.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTWords(@SuppressWarnings("unused") TWords node)
    {
        this.index = 0;
    }

    @Override
    public void caseTOperation(@SuppressWarnings("unused") TOperation node)
    {
        this.index = 1;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 2;
    }
}
